refactor: extract helper functions from pmp_cma

diff --git a/pmp b/pmp
--- a/pmp
+++ b/pmp
@@ -323,62 +323,80 @@ Others commands will be passed to git, you can type 'git help <cmd>' for help.
 EOF
 )
     local cmd=$1 && shift
-    local obj
 
     case $cmd in
-        pin)   for obj in "$@"; do pmp_git config "cmd.$obj" true; done ;;
-        unpin) for obj in "$@"; do pmp_git config --unset "cmd.$obj" ; done ;;
-        keep)
-            [[ $# -eq 1 || $# -eq 2 ]] || die "Usage: pmp keep <config> [target]"
-            [[ -e $1 ]] || die "No such file or directory."
-
-            local cfg="$1" && [[ $cfg =~ ^/ ]] || cfg="$PWD/$cfg"
-            local source="$(readlink -f "$cfg")"
-            local target="$PMP_REPO/${2:-$(basename "$cfg")}"
-
-            [[ ! -e $target ]] || die "Configuration file or directory is already exist: $target"
-
-            # if it's user dotfiles, use $HOME as path prefix
-            [[ ! $cfg =~ $HOME ]] || cfg="${cfg/$HOME/\$HOME}"
-
-            [[ -d ${target%/*} ]] || mkdir -p "${target%/*}"
-            # copy and backup the configurations first
-            cp -rp "$source" "$target" && eval mv "$cfg" "$cfg-$(date +%Y%m%d%H%M%S)" \
-                && eval ln -s "$(readlink -f "$target")" "$cfg" \
-                && pmp_git config "cfg.'${target##"$PMP_REPO"/}'.link" "$cfg" \
-                && pmp_git add "$PMP_CONF" "${target##"${PMP_REPO}"/}" \
-                && pmp_git commit -m "keep $cfg" \
-                || die "Failed to keep $1"
-            ;;
-        free)
-            [[ $# -gt 0 ]] || die "Usage: pmp free <config> ..."
-
-            local origin=""
-
-            for cfg in "$@"; do
-                [[ -e $PMP_REPO/$cfg ]] || error "No such file or directory in repo: $cfg" || continue
-                if pmp config --get-regexp "cfg.'$cfg'.link" &>/dev/null; then
-                    origin="$(pmp config --get-regexp "cfg.'$cfg'.link" 2>/dev/null | awk '{print $2}')"
-                    [[ -e $origin ]] || warn "Can not find the link: $origin -> $cfg" >&2
-                    eval rm -rf "$origin" && eval cp -rp "$PMP_REPO/$cfg" "$origin" \
-                        && pmp_git config --unset "cfg.'$cfg'.link" \
-                        && pmp_git add "$PMP_CONF" \
-                        && pmp_git rm -r "$cfg" \
-                        && pmp_git commit -m "free $cfg" \
-                        || error "Failed to free $cfg"
-                else
-                    error "${cfg@Q} is not directly kept as a file, maybe kept in a directory."
-                fi
-            done
-            return "$PMP_EXIT_CODE"
-            ;;
-        sync)
-            ;;
-        deps)
-            ;;
+        pin) pmp_cma_pin "$@" ;;
+        unpin) pmp_cma_unpin "$@" ;;
+        keep) pmp_cma_keep "$@" ;;
+        free) pmp_cma_free "$@" ;;
+        sync) pmp_cma_sync "$@" ;;
+        deps) pmp_cma_deps "$@" ;;
         help) usage ;;
         *) die "No such command: ${cmd@Q}" ;;
     esac
+}
+
+pmp_cma_pin() {
+    for obj in "$@"; do pmp_git config "cmd.$obj" true; done
+}
+
+pmp_cma_unpin() {
+    for obj in "$@"; do pmp_git config --unset "cmd.$obj" ; done
+}
+
+pmp_cma_keep() {
+    ensure "[[ $# -eq 1 || $# -eq 2 ]]" "Usage: pmp keep <config> [target]"
+
+    [[ -e $1 ]] || die "No such file or directory."
+
+    local cfg="$1" && [[ $cfg =~ ^/ ]] || cfg="$PWD/$cfg"
+    local source="$(readlink -f "$cfg")"
+    local target="$PMP_REPO/${2:-$(basename "$cfg")}"
+
+    [[ ! -e $target ]] || die "Configuration file or directory is already exist: $target"
+
+    # if it's user dotfiles, use $HOME as path prefix
+    [[ ! $cfg =~ $HOME ]] || cfg="${cfg/$HOME/\$HOME}"
+
+    [[ -d ${target%/*} ]] || mkdir -p "${target%/*}"
+    # copy and backup the configurations first
+    cp -rp "$source" "$target" && eval mv "$cfg" "$cfg-$(date +%Y%m%d%H%M%S)" \
+        && eval ln -s "$(readlink -f "$target")" "$cfg" \
+        && pmp_git config "cfg.'${target##"$PMP_REPO"/}'.link" "$cfg" \
+        && pmp_git add "$PMP_CONF" "${target##"${PMP_REPO}"/}" \
+        && pmp_git commit -m "keep $cfg" \
+        || die "Failed to keep $1"
+}
+
+pmp_cma_free() {
+    ensure "[[ $# -gt 0 ]]" "Usage: pmp free <config> ..."
+
+    local origin=""
+
+    for cfg in "$@"; do
+        [[ -e $PMP_REPO/$cfg ]] || error "No such file or directory in repo: $cfg" || continue
+        if pmp config --get-regexp "cfg.'$cfg'.link" &>/dev/null; then
+            origin="$(pmp config --get-regexp "cfg.'$cfg'.link" 2>/dev/null | awk '{print $2}')"
+            [[ -e $origin ]] || warn "Can not find the link: $origin -> $cfg" >&2
+            eval rm -rf "$origin" && eval cp -rp "$PMP_REPO/$cfg" "$origin" \
+                && pmp_git config --unset "cfg.'$cfg'.link" \
+                && pmp_git add "$PMP_CONF" \
+                && pmp_git rm -r "$cfg" \
+                && pmp_git commit -m "free $cfg" \
+                || error "Failed to free $cfg"
+        else
+            error "${cfg@Q} is not directly kept as a file, maybe kept in a directory."
+        fi
+    done
+    return "$PMP_EXIT_CODE"
+}
+
+pmp_cma_sync() {
+    :
+}
+
+pmp_cma_deps() {
+    :
 }
 
 pmp_link_repo() {
